export const GACHA_PRESET_REWARDS = [
  {
    name: "月露茶券",
    description: "一杯热饮或奶茶，适合完成轻量目标后的即时奖励。",
    emoji: "☕",
    imageUrl: "/gacha/items/moon-tea.svg",
    tier: "common",
    costGold: 30,
    costGems: 0,
    inGachaPool: true,
    weight: 8,
  },
  {
    name: "星糖点心",
    description: "给自己买一份甜点，不需要额外理由。",
    emoji: "🍰",
    imageUrl: "/gacha/items/starlit-macaron.svg",
    tier: "common",
    costGold: 35,
    costGems: 0,
    inGachaPool: true,
    weight: 8,
  },
  {
    name: "风之空白券",
    description: "30 分钟自由时间，完全不安排任务。",
    emoji: "🪁",
    imageUrl: "/gacha/items/glider-ticket.svg",
    tier: "common",
    costGold: 45,
    costGems: 0,
    inGachaPool: true,
    weight: 7,
  },
  {
    name: "安眠烛",
    description: "提前收工、泡澡或做一次睡前放松仪式。",
    emoji: "🕯️",
    imageUrl: "/gacha/items/dream-candle.svg",
    tier: "common",
    costGold: 60,
    costGems: 0,
    inGachaPool: true,
    weight: 6,
  },
  {
    name: "蔚蓝书契",
    description: "买一本书、课程资料或知识产品。",
    emoji: "📘",
    imageUrl: "/gacha/items/azure-book.svg",
    tier: "rare",
    costGold: 220,
    costGems: 1,
    inGachaPool: true,
    weight: 5,
  },
  {
    name: "樱宴席券",
    description: "一次喜欢的餐厅、外卖或料理体验。",
    emoji: "🍱",
    imageUrl: "/gacha/items/sakura-meal.svg",
    tier: "rare",
    costGold: 320,
    costGems: 2,
    inGachaPool: true,
    weight: 5,
  },
  {
    name: "云息疗愈",
    description: "按摩、理疗、运动恢复或一次深度休息。",
    emoji: "💆",
    imageUrl: "/gacha/items/cloud-massage.svg",
    tier: "rare",
    costGold: 420,
    costGems: 2,
    inGachaPool: true,
    weight: 4,
  },
  {
    name: "灵感晶笔",
    description: "一件小型创作工具、文具或数字插件。",
    emoji: "✒️",
    imageUrl: "/gacha/items/crystal-pen.svg",
    tier: "rare",
    costGold: 480,
    costGems: 3,
    inGachaPool: true,
    weight: 4,
  },
  {
    name: "远野地图",
    description: "周末短途旅行、城市探索或半日外出预算。",
    emoji: "🗺️",
    imageUrl: "/gacha/items/horizon-map.svg",
    tier: "epic",
    costGold: 900,
    costGems: 8,
    inGachaPool: true,
    weight: 3,
  },
  {
    name: "匠心礼匣",
    description: "购买一件犹豫很久、能提升生活质量的好物。",
    emoji: "🎁",
    imageUrl: "/gacha/items/artisan-box.svg",
    tier: "epic",
    costGold: 1200,
    costGems: 10,
    inGachaPool: true,
    weight: 2,
  },
  {
    name: "极光工坊",
    description: "关键设备、生产力硬件或工作流升级预算。",
    emoji: "⌨️",
    imageUrl: "/gacha/items/aurora-keyboard.svg",
    tier: "legendary",
    costGold: 3200,
    costGems: 30,
    inGachaPool: true,
    weight: 1,
  },
  {
    name: "星海通行证",
    description: "长线旅行、大型体验或年度级愿望预算。",
    emoji: "✈️",
    imageUrl: "/gacha/items/astral-passport.svg",
    tier: "legendary",
    costGold: 5000,
    costGems: 50,
    inGachaPool: true,
    weight: 1,
  },
] as const;
