export const GACHA_PRESET_REWARDS = [
  {
    name: "月露茶券",
    description: "一杯热饮或奶茶，适合完成轻量目标后的即时奖励。",
    emoji: "☕",
    imageUrl: "/gacha/items/material-moon-tea.png",
    tier: "common",
    category: "physical_small",
    costMoneyCents: 2800,
    costGold: 30,
    inGachaPool: true,
    weight: 8,
  },
  {
    name: "星糖点心",
    description: "给自己买一份甜点，不需要额外理由。",
    emoji: "🍰",
    imageUrl: "/gacha/items/material-starlit-treat.png",
    tier: "common",
    category: "physical_small",
    costMoneyCents: 3500,
    costGold: 35,
    inGachaPool: true,
    weight: 8,
  },
  {
    name: "风之空白券",
    description: "30 分钟自由时间，完全不安排任务。",
    emoji: "🪁",
    imageUrl: "/gacha/items/material-free-time-ticket.png",
    tier: "common",
    category: "virtual",
    costMoneyCents: 0,
    costGold: 45,
    inGachaPool: true,
    weight: 7,
  },
  {
    name: "安眠烛",
    description: "提前收工、泡澡或做一次睡前放松仪式。",
    emoji: "🕯️",
    imageUrl: "/gacha/items/material-dream-rest.png",
    tier: "common",
    category: "physical_small",
    costMoneyCents: 4500,
    costGold: 60,
    inGachaPool: true,
    weight: 6,
  },
  {
    name: "蔚蓝书契",
    description: "买一本书、课程资料或知识产品。",
    emoji: "📘",
    imageUrl: "/gacha/items/material-azure-book.png",
    tier: "rare",
    category: "physical_small",
    costMoneyCents: 8000,
    costGold: 220,
    inGachaPool: true,
    weight: 5,
  },
  {
    name: "樱宴席券",
    description: "一次喜欢的餐厅、外卖或料理体验。",
    emoji: "🍱",
    imageUrl: "/gacha/items/material-sakura-voucher.png",
    tier: "rare",
    category: "physical_small",
    costMoneyCents: 12000,
    costGold: 320,
    inGachaPool: true,
    weight: 5,
  },
  {
    name: "云息疗愈",
    description: "按摩、理疗、运动恢复或一次深度休息。",
    emoji: "💆",
    imageUrl: "/gacha/items/material-cloud-healing.png",
    tier: "rare",
    category: "physical_small",
    costMoneyCents: 30000,
    costGold: 420,
    inGachaPool: true,
    weight: 4,
  },
  {
    name: "灵感晶笔",
    description: "一件小型创作工具、文具或数字插件。",
    emoji: "✒️",
    imageUrl: "/gacha/items/material-crystal-tool.png",
    tier: "rare",
    category: "physical_small",
    costMoneyCents: 20000,
    costGold: 480,
    inGachaPool: true,
    weight: 4,
  },
  {
    name: "远野地图",
    description: "周末短途旅行、城市探索或半日外出预算。",
    emoji: "🗺️",
    imageUrl: "/gacha/items/material-horizon-map.png",
    tier: "epic",
    category: "physical_large",
    costMoneyCents: 80000,
    costGold: 900,
    inGachaPool: true,
    weight: 3,
  },
  {
    name: "匠心礼匣",
    description: "购买一件犹豫很久、能提升生活质量的好物。",
    emoji: "🎁",
    imageUrl: "/gacha/items/material-artisan-gift.png",
    tier: "epic",
    category: "physical_large",
    costMoneyCents: 69900,
    costGold: 1200,
    inGachaPool: true,
    weight: 2,
  },
  {
    name: "极光工坊",
    description: "关键设备、生产力硬件或工作流升级预算。",
    emoji: "⌨️",
    imageUrl: "/gacha/items/material-aurora-workshop.png",
    tier: "legendary",
    category: "physical_large",
    costMoneyCents: 129900,
    costGold: 3200,
    inGachaPool: true,
    weight: 1,
  },
  {
    name: "星海通行证",
    description: "长线旅行、大型体验或年度级愿望预算。",
    emoji: "✈️",
    imageUrl: "/gacha/items/material-astral-pass.png",
    tier: "legendary",
    category: "physical_large",
    costMoneyCents: 300000,
    costGold: 5000,
    inGachaPool: true,
    weight: 1,
  },
] as const;
